export const tags = [
  "web",
  "developer",
  "portfolio",
  "luke",
  "lucas",
  "climenhage",
  "luke climenhage",
  "lucas climenhage",
  "Luke",
  "Lucas",
  "Climenhage",
  "Luke Climenhage",
  "Lucas Climenhage",
  "hrfolio",
  "hr",
  "folio",
  "hr folio",
  "Canada",
  "Kitchener",
  "Waterloo",
  "Kitchener Waterloo",
  "Ontario",
  "Canada",
  "Kitchener Ontario",
  "Waterloo Ontario",
  "design",
];
